SET SERVEROUTPUT ON;

SET SERVEROUTPUT ON SIZE 100000;
ALTER SESSION SET CURRENT_SCHEMA = AUTOPARTS_OWNER;
SELECT USER FROM dual;
---
SET LINESIZE 6000
COLUMN PRODUCT_ID FORMAT 9999
COLUMN NAME FORMAT A40 WORD_WRAP
COLUMN CATEGORY FORMAT A25
COLUMN BRAND FORMAT A20
COLUMN DESCRIPTION FORMAT A50 WORD_WRAP 
COLUMN PRICE FORMAT 999.99
COLUMN QUANTITY_IN_STOCK FORMAT 9999
COLUMN AVAILABILITY FORMAT A15
SET PAGESIZE 50

-- 1. create_user(имя, пароль, роль, имя, фамилия, email, телефон);
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.CREATE_USER('ggUS', 'gg777', 'user', 'Имя', 'Фамилия', 'admin12345@auto.by', '+375297558929');

EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.GET_ALL_USERS;
-- 2. Выдать роль менеджер пользователю
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.SET_USER_ROLE(24, 'user');

-- 3. add_product(название товара, id категории, id поставщика, цена, кол-во, описание);
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.get_all_catalog;
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.get_all_categories;
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.get_all_vendors;
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.ADD_PRODUCT('Тормозные диски Mercedes', 3, 1, 150, 20, 'Премиум качество');
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.print_products_by_category(3);



-- 13. Добавление категории
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.ADD_CATEGORY('Автохимия Тестовая');
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.get_all_categories;
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.print_products_by_category(41);
-- Добавление, удаление, обновление товара
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.ADD_PRODUCT('ТОВАР_ТЕСТ3', 41, 41, '17.89', 10, 'Высококонцентрированный состав');
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.UPDATE_PRODUCT(61, 'Shell Helix Ultra 5W-40 4L', '90', 10);
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.REMOVE_PRODUCT(21);

EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.get_all_catalog;

-- 14. Изменить данные категории (ID 10)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.UPDATE_CATEGORY(21, 'Зимняя Автохимия');

-- Удалить товары категории и саму категорию (ID 10)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.WIPE_CATEGORY(5);


-- 7. Вывод всех пользователей (без маскировки)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.GET_ALL_USERS;

-- 8. Удалить товар (ID 50)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.REMOVE_PRODUCT(21);
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.get_all_catalog;

-- 9. Добавить поставщика
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.get_all_vendors;
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.ADD_VENDOR('ООО АвтоМир123', '+375298887766', 'sales123@automir.by');

EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.UPDATE_VENDOR(21, 'АвтоБай', '+375172000001', 'salesS@armtek.by');
-- 10. Удалить поставщика (ID 5)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.REMOVE_VENDOR(21);



-- 15. Блокировка и разблокировка пользователя (ID 5)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.GET_ALL_USERS;

EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.BLOCK_USER(24);
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.UNBLOCK_USER(24);


EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.EXPORT_LOGS_JSON('activity.json');
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.CLEAR_ACTIVITY_LOGS;
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.IMPORT_LOGS_JSON('activity.json');

--SELECT * FROM ACTIVITY_LOGS;
-- 6. Отчет по продажам за месяц
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.SALES_REPORT('05.12.2025', '05.12.2025');
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_ADMIN.total_print;
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.trending_products;

