SET SERVEROUTPUT ON;

SET SERVEROUTPUT ON SIZE 100000;
ALTER SESSION SET CURRENT_SCHEMA = AUTOPARTS_OWNER;
SELECT USER FROM dual;
---
SET LINESIZE 6000
COLUMN PRODUCT_ID FORMAT 9999
COLUMN NAME FORMAT A40 WORD_WRAP
COLUMN CATEGORY FORMAT A25
COLUMN BRAND FORMAT A20
COLUMN DESCRIPTION FORMAT A50 WORD_WRAP 
COLUMN PRICE FORMAT 999.99
COLUMN QUANTITY_IN_STOCK FORMAT 9999
COLUMN AVAILABILITY FORMAT A15
SET PAGESIZE 50

EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.get_all_catalog;
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.get_all_categories;

-- 1. Просмотр всех заказов
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_MANAGER.GET_ALL_ORDERS;
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_MANAGER.GET_ALL_ORDERS(2);

-- 2. Изменить статус заказа (Заказ 1 -> Shipped)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_MANAGER.UPDATE_ORDER_STATUS(400001, 'Cancelled');

-- 3. Установить товар "Нет в наличии" (Товар 3)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_MANAGER.SET_STOCK(41, 'Нет в наличии');

-- 3. Вернуть товар "В наличии"
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_MANAGER.SET_STOCK(6, 'В наличии');

-- 5. Информация о товаре (Товар 3)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_MANAGER.CHECK_PRODUCT(6);

-- 4. Вывод всех поставщиков
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_MANAGER.GET_ALL_VENDORS;

-- 6. Вывод всех пользователей (маскированные данные)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_MANAGER.GET_ALL_USERS;

