SET SERVEROUTPUT ON;
SET SERVEROUTPUT ON SIZE 100000;
ALTER SESSION SET CURRENT_SCHEMA = AUTOPARTS_OWNER;
SELECT USER FROM dual;
---
SET LINESIZE 6000
COLUMN PRODUCT_ID FORMAT 9999
COLUMN NAME FORMAT A40 WORD_WRAP
COLUMN CATEGORY FORMAT A25
COLUMN BRAND FORMAT A20
COLUMN DESCRIPTION FORMAT A50 WORD_WRAP 
COLUMN PRICE FORMAT 999.99
COLUMN QUANTITY_IN_STOCK FORMAT 9999
COLUMN AVAILABILITY FORMAT A15
SET PAGESIZE 50

-- Регистрация нового пользователя
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.REGISTER_USER('Sidor', 'password123', 'Алексей', 'Сидоров', 'sidorov123@mail.by', '+375291112233');

-- Вход в аккаунт
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.LOGIN_USER('Sidor', 'password123');

-- 1. Просмотр всего каталога
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.GET_ALL_CATALOG;

-- 2. Просмотр всех категорий
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.GET_ALL_CATEGORIES;

-- 3. Просмотр товаров конкретной категории
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.PRINT_PRODUCTS_BY_CATEGORY(3);

-- 5. Добавить товар в корзину (Пользователь 45, id товара 70, кол-во 25)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.ADD_TO_CART(42, 41, 1);

-- 4. Просмотреть корзину (Пользователь 45)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.SHOW_CART(42);

-- 6. Изменить кол-во товара в корзине (Позиция товара в корзине 1, новое кол-во 25)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.CHANGE_COUNT_CART(42, 1, 20);

-- 7. Добавить еще один товар (Пользователь 45, id товара 69, кол-во 25)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.ADD_TO_CART(42, 9, 100);

-- 8. Удалить товар из корзины (Пользователь 45, Позиция товара в корзине 2)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.REMOVE_FROM_CART(42, 2);

-- 8.1 Начать оформление заказа (Пользователь 45)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.START_CHECKOUT(42);

-- 8.2 Добавить инфо о доставке (на завтра)
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.ADD_DELIVERY_INFO(42, 'Минск, ул. Ленина 5-12', '01-02-2026');

-- 9. Оформить заказ
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.CREATE_ORDER_FROM_CART(42);

-- 10. Просмотреть историю заказов
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.USER_ORDERS(42);

-- 11. Популярные товары
EXEC AUTOPARTS_OWNER.AUTOPARTS_API_USER.TRENDING_PRODUCTS;