


CREATE INDEX IDX_ORDERS_STATUS_DATE ON ORDERS(STATUS, ORDER_DATE);

EXPLAIN PLAN FOR
SELECT STATUS, COUNT(*) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY STATUS;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
