-- 1. Создание Pluggable Database 
-- opt/oracle/oradata/XE/autoparts_pdb
-- opt/oracle/oradata/XE/pdbseed
CREATE PLUGGABLE DATABASE AUTOPARTS_PDB ADMIN USER pdb_admin IDENTIFIED BY "123"
FILE_NAME_CONVERT = ('/pdbseed/', '/autoparts_pdb/');
/
ALTER PLUGGABLE DATABASE AUTOPARTS_PDB OPEN;
ALTER PLUGGABLE DATABASE AUTOPARTS_PDB SAVE STATE;
ALTER SESSION SET CONTAINER = AUTOPARTS_PDB;
/
-- 3. Создание табличных пространств
CREATE TABLESPACE TS_CORE 
    DATAFILE 'ts_core.dbf' 
    SIZE 200M 
    AUTOEXTEND ON 
    NEXT 50M 
    MAXSIZE 2G;
/
CREATE TABLESPACE TS_PRODUCTS 
    DATAFILE 'ts_products.dbf' 
    SIZE 500M 
    AUTOEXTEND ON 
    NEXT 100M 
    MAXSIZE 5G;
/
CREATE TABLESPACE TS_ARCHIVE 
    DATAFILE 'ts_archive.dbf' 
    SIZE 500M 
    AUTOEXTEND ON 
    NEXT 100M 
    MAXSIZE 5G;
/
-- 4. Создание профиля безопасности SECURE_PROFILE 
CREATE PROFILE SECURE_PROFILE LIMIT
  FAILED_LOGIN_ATTEMPTS 3 -- Блок учетной записи после 3 неудачных попыток
  PASSWORD_LIFE_TIME 90 -- Пароль истекает через 90 дней
  PASSWORD_LOCK_TIME 1 -- Если аккаунт заблокирован из-за неверного пароля 3 раза, то блокируется на 1 день
  SESSIONS_PER_USER 5 -- Пользователь может иметь не более 5 одновременных подключений к БД
  IDLE_TIME 30; -- Сессия завершается, если нет активности в течение 30 минут
/
  -- 6. Создание Владельца Схем
CREATE USER AUTOPARTS_OWNER IDENTIFIED BY "123"
    DEFAULT TABLESPACE TS_CORE
    QUOTA UNLIMITED ON TS_CORE
    QUOTA UNLIMITED ON TS_PRODUCTS
    QUOTA UNLIMITED ON TS_ARCHIVE
    PROFILE SECURE_PROFILE;
/
-- 7. Привилегии для AUTOPARTS_OWNER
GRANT CREATE ANY TABLE, ALTER ANY TABLE, DROP ANY TABLE TO AUTOPARTS_OWNER;
GRANT SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO AUTOPARTS_OWNER;
GRANT CREATE ANY INDEX, ALTER ANY INDEX, DROP ANY INDEX TO AUTOPARTS_OWNER;
GRANT CREATE ANY VIEW, DROP ANY VIEW TO AUTOPARTS_OWNER;
GRANT CREATE ANY PROCEDURE, ALTER ANY PROCEDURE, DROP ANY PROCEDURE, EXECUTE ANY PROCEDURE TO AUTOPARTS_OWNER;
GRANT CREATE ANY TRIGGER, ALTER ANY TRIGGER, DROP ANY TRIGGER TO AUTOPARTS_OWNER;
GRANT CREATE ANY SEQUENCE, ALTER ANY SEQUENCE, DROP ANY SEQUENCE TO AUTOPARTS_OWNER;
GRANT CREATE USER, ALTER USER, DROP USER TO AUTOPARTS_OWNER;
GRANT CREATE SESSION, ALTER SESSION TO AUTOPARTS_OWNER WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO AUTOPARTS_OWNER;
GRANT CREATE TABLESPACE, ALTER TABLESPACE, DROP TABLESPACE TO AUTOPARTS_OWNER;
GRANT CREATE ROLE, DROP ANY ROLE, ALTER ANY ROLE, GRANT ANY ROLE TO AUTOPARTS_OWNER;
GRANT CREATE PROFILE, DROP PROFILE, ALTER PROFILE TO AUTOPARTS_OWNER;
GRANT CREATE USER, ALTER USER, DROP USER TO AUTOPARTS_OWNER;
CREATE OR REPLACE DIRECTORY DATA_EXPORT_DIR AS '/opt/oracle/admin/XE/';
GRANT READ, WRITE ON DIRECTORY DATA_EXPORT_DIR TO PUBLIC;
GRANT EXECUTE ON DBMS_CRYPTO TO AUTOPARTS_OWNER;
/
--5 Первоначально нужно создать пакеты AUTOPARTS_API (AUTOPARTS_OWNER)
--5.1 Создать все таблицы и индексы (AUTOPARTS_OWNER)
--5.2 Создать все представления (AUTOPARTS_OWNER)
--5.3 Создать все триггеры (AUTOPARTS_OWNER)
--5.4 Добавить данные в таблицы
--5.5 Создание тестовых пользователей
--5.6 Создание ролей (AUTOPARTS_OWNER) 
CREATE ROLE ADMIN_ROLE;
CREATE ROLE MANAGER_ROLE;
CREATE ROLE USER_ROLE;
--GRANT ADMIN_ROLE, MANAGER_ROLE, USER_ROLE TO AUTOPARTS_OWNER WITH ADMIN OPTION;

GRANT EXECUTE ON AUTOPARTS_API_USER TO USER_ROLE;
GRANT EXECUTE ON AUTOPARTS_API_MANAGER TO USER_ROLE;
GRANT EXECUTE ON AUTOPARTS_API_ADMIN TO USER_ROLE;

GRANT EXECUTE ON AUTOPARTS_API_ADMIN TO MANAGER_ROLE;
GRANT EXECUTE ON AUTOPARTS_API_MANAGER TO MANAGER_ROLE;
GRANT EXECUTE ON AUTOPARTS_API_USER TO MANAGER_ROLE;

GRANT EXECUTE ON AUTOPARTS_API_ADMIN TO ADMIN_ROLE;
GRANT EXECUTE ON AUTOPARTS_API_MANAGER TO ADMIN_ROLE;
GRANT EXECUTE ON AUTOPARTS_API_USER TO ADMIN_ROLE;

-- 4. Общие утилиты (нужны всем для работы внутренней логики)
GRANT EXECUTE ON AUTOPARTS_UTIL TO USER_ROLE;
GRANT EXECUTE ON AUTOPARTS_UTIL TO MANAGER_ROLE;
GRANT EXECUTE ON AUTOPARTS_UTIL TO ADMIN_ROLE;

--9. Создаем пользователя ADMIN1
CREATE USER ADMIN1 IDENTIFIED BY "123"
  DEFAULT TABLESPACE TS_CORE
  QUOTA UNLIMITED ON TS_CORE
  PROFILE SECURE_PROFILE;
  
CREATE USER USER1 IDENTIFIED BY "123"
  DEFAULT TABLESPACE TS_CORE
  QUOTA UNLIMITED ON TS_CORE
  PROFILE SECURE_PROFILE;
  
CREATE USER MANAGER1 IDENTIFIED BY "123"
  DEFAULT TABLESPACE TS_CORE
  QUOTA UNLIMITED ON TS_CORE
  PROFILE SECURE_PROFILE;
  
GRANT ADMIN_ROLE TO ADMIN1;
GRANT CREATE SESSION TO ADMIN1;

GRANT USER_ROLE TO USER1;
GRANT CREATE SESSION TO USER1;

GRANT MANAGER_ROLE TO MANAGER1;
GRANT CREATE SESSION TO MANAGER1;


BEGIN
    INSERT INTO USERS (USERNAME, PASSWORD_HASH, ROLE, FIRST_NAME, LAST_NAME, PHONE, EMAIL, IS_BLOCKED, REGISTERED_DATE, IS_ACTIVE) 
    VALUES ('ADMIN1', AUTOPARTS_UTIL.HASH_PASS('123'), 'admin', 'Админ', 'Админ', '+375291001010', 'admin@autoparts.com', 'N', SYSDATE, 'Y');
    
    INSERT INTO USERS (USERNAME, PASSWORD_HASH, ROLE, FIRST_NAME, LAST_NAME, PHONE, EMAIL, IS_BLOCKED, REGISTERED_DATE, IS_ACTIVE) 
    VALUES ('MANAGER1', AUTOPARTS_UTIL.HASH_PASS('123'), 'manager', 'Менеджер', 'Менеджер', '+375291001011', 'manager@autoparts.com', 'N', SYSDATE, 'Y');
    
    INSERT INTO USERS (USERNAME, PASSWORD_HASH, ROLE, FIRST_NAME, LAST_NAME, PHONE, EMAIL, IS_BLOCKED, REGISTERED_DATE, IS_ACTIVE) 
    VALUES ('USER1', AUTOPARTS_UTIL.HASH_PASS('123'), 'user', 'Пользователь', 'Пользователь', '+375291001012', 'user@autoparts.com', 'N', SYSDATE, 'Y');
    -- Создаем корзину для клиента
    INSERT INTO SHOPPING_CARTS (USER_ID) VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME = 'USER1'));
    COMMIT;
END;
/
select * from users;
-- 10. 100k
